openapi: 3.0.0
info:
  version: '1.0'
  title: Lbaw Project
  description: Web Resources Specification (A7) for Lbaw Project
    
externalDocs:
  description: "Get more information here."
  url: https://git.fe.up.pt/lbaw/lbaw2122/lbaw2125/

tags:
  - name: "M01: Authentication and Individual Profile"
  - name: "M02: Individual Profile"
  - name: "M03: Categories"
  - name: "M04: Content Interaction"
  - name: "M05: Static Pages"
paths:
  # M01: Authentication and Individual Profile
  /login:
    get:
      operationId: R101
      summary: "R101: Login Form"
      description: "Provide login form. Access: PUB"
      tags:
        - "M01: Authentication and Individual Profile"
      responses:
        "200":
          description: "Ok. Show [UI04 Sign-in](https://git.fe.up.pt/lbaw/lbaw2122/lbaw2125/-/wikis/er#ui01homepage)"
    post:
      operationId: R102
      summary: "R102: Login Action"
      description: "Processes the login form submission. Access: PUB"
      tags:
        - "M01: Authentication and Individual Profile"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        "302":
          description: "Redirect after processing the login credentials."
          headers:
            location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Successful authentication, redirecting to home page"
                  value: "/"
                302Error:
                  description: "Failed to authenticate. Returning to login form"
                  value: "/login"
  /logout:
    post:
      operationId: R103
      summary: "R103: Sign-out"
      description: "Sign-out the current authenticated user. Access: USR, ADM"
      tags:
        - "M01: Authentication and Individual Profile"
      responses:
        "302":
          description: "Redict after processing sign-out"
          headers:
            location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Sign-out successful. Redirecting to home page"
                  value: "/"

  /register:
    get:
      operationId: R104
      summary: "R104: Register Form"
      description: "Provide a new user registration form. Access: PUB"
      tags:
        - "M01: Authentication and Individual Profile"
      responses:
        "200":
          description: "Ok. Show [UI05 Sign-up](https://git.fe.up.pt/lbaw/lbaw2122/lbaw2125/-/wikis/er#ui05-sign-up)"

    post:
      operationId: R105
      summary: "R105: Register new user"
      description: "Processes the form information to register new user. Access: PUB"
      tags:
        - "M01: Authentication and Individual Profile"

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                email:
                  type: string
                  format: email
                phone:
                  type: string
                  format: phone
                password:
                  type: string
                  format: password
                confirmationPassword:
                  type: string
                  format: password
                termsService:
                  type: boolean
              required:
                - name
                - username
                - email
                - phone
                - password
                - confirmationPassword
                - termsService

      responses:
        "302":
          description: "Redirect after processing new user information"
          headers:
            location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Sucessful registration. Redirecting to home page"
                  value: "/"
                302Error:
                  description: "Failed registration. Redirecting back to register form"
                  value: "/register"
  /user/me:
    get:
      operationId: R106
      summary: "R106: View your profile"
      description: "Show user's profile Access: USR"
      tags:
        - "M01: Authentication and Individual Profile"
      responses:
        "200":
          description: "Ok. Show [UI02 Sign-in](https://git.fe.up.pt/lbaw/lbaw2122/lbaw2125/-/blob/main/ER.md#ui02profile)"
