openapi: 3.0.0
info:
  version: '1.0'
  title: Lbaw Project
  description: Web Resources Specification (A7) for Lbaw Project
    
externalDocs:
  description: "Get more information here."
  url: https://git.fe.up.pt/lbaw/lbaw2223/lbaw2212

tags:
  - name: "M01: Authentication"
  - name: "M02: User"
  - name: "M03: User Notifications"
  - name: "M04: Post"
  - name: "M05: Comment"
  - name: "M06: Reaction"
paths:
  /login:
    get:
      operationId: R101
      summary: "R101: Login Form"
      description: "Provide login form. Access: PUB"
      tags:
        - "M01: Authentication"
      responses:
        "200":
          description: "Return login page."
    post:
      operationId: R102
      summary: "R102: Login Action"
      description: "Processes the login form data. Access: PUB"
      tags:
        - "M01: Authentication"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
              required:
                - username
                - password
      responses:
        "302":
          description: "Redirect after processing the login credentials."
          headers:
            location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Login succeed. Will redirect to user feed."
                  value: "/"
        "401":
          description: "Redirect after processing the login credentials."
          headers:
            location:
              schema:
                type: string
              examples:
                401Error:
                  description: "Unauthorized. Response will be processed in the login page to alert the user about the failure."
                  value: "/login"
  /logout:
    post:
      operationId: R103
      summary: "R103: Sign-out"
      description: "Sign-out the current authenticated user. Access: USR, ADM"
      tags:
        - "M01: Authentication"
      responses:
        "302":
          description: "Redict after processing sign-out"
          headers:
            location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Sign-out successful. Redirecting to home page"
                  value: "/"

  /register:
    get:
      operationId: R104
      summary: "R104: Register Form"
      description: "Provide a new user registration form. Access: PUB"
      tags:
        - "M01: Authentication"
      responses:
        "200":
          description: "Show Register Page to User. Access: PUB"

    post:
      operationId: R105
      summary: "R105: Register new user"
      description: "Processes the form information to register new user. Access: PUB"
      tags:
        - "M01: Authentication"

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                name:
                  type: string
                gender:
                  type: string
                password:
                  type: string
                  format: password
                description:
                  type: string
                photo:
                  type: blob
              required:
                - username
                - email
                - name
                - gender
                - password

      responses:
        "302":
          description: "Redirect after processing new user information"
          headers:
            location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Sucessful registration. Redirecting to home page"
                  value: "/"
                302Error:
                  description: "Failed registration. Redirecting back to register form"
                  value: "/register"

  /user:
    get:
      operationId: R201
      summary: "R201: User Profile"
      description: "Show user profile. Access: USR, ADM"
      tags:
        - "M02: User"
      responses:
        "200":
          description: "Show user profile page. Access: USR, ADM"
    put:
      operationId: R202
      summary: "R202: Edit User Profile"
      description: "Edit user profile. Access: USR, ADM"
      tags:
        - "M02: User"
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                gender:
                  type: string
                password:
                  type: string
                  format: password
                description:
                  type: string
                photo:
                  type: blob

    delete:
      operationId: R203
      summary: "R203: Delete User Profile"
      description: "Delete user profile. Access: ADM"
      tags:
        - "M02: User"
      responses:
        "302":
          description: "Redirect after processing user deletion"
          headers:
            location:
              schema:
                type: string
              examples:
                302Success:
                  description: "Sucessful deletion. Redirecting to home page"
                  value: "/"
                302Error:
                  description: "Failed deletion. Redirecting back to user profile"
                  value: "/user"
  


  /notification: # use get notification to get all notifications as JSON
    get:
      operationId: R204
      summary: "R204: Get Notifications"
      description: "Get all notifications. Access: USR, ADM"
      tags:
        - "M03: User Notifications"
      responses:
        "200":
          description: "Show all notifications. Access: USR, ADM"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    type:
                      type: string
                    content:
                      type: string
                    date:
                      type: string
                      format: date-time
                    read:
                      type: boolean
                    text :
                      type: string

  /notification/{id}: # update the notification to set it as read
    put:
      operationId: R205
      summary: "R205: Update Notification"
      description: "Update notification to set it as read. Access: USR, ADM"
      tags:
        - "M03: User Notifications"
      parameters:
        - name: id
          in: path
          description: "Notification ID"
          required: true
          schema:
            type: integer
        - name: read
          in: query
          description: "If notification was read"
          required: true
          schema:
            type: boolean
      responses:
        "200":
          description: "Update notification. Access: USR, ADM"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                
